#!/bin/bash
set -e
green=$(tput setaf 2)
red=$(tput setaf 1)
bold=$(tput bold)
normal=$(tput sgr0)

print_step_status() {
    local step_length=$(expr length "${1}")
    let x=40-${step_length}

    printf "%s%${x}s\n" "${1}" "${2}"
}

hash rebar 2>/dev/null || { echo >&2 "Can not find rebar, aborting installation."; exit 1; }
print_step_status "Check dependencies" "${green}${bold}DONE${normal}"

make all &> /dev/null
print_step_status "Compiling" "${green}${bold}DONE${normal}"

make tests &> /dev/null
print_step_status "Tests" "${green}${bold}DONE${normal}"

echo "Installation completed, have fun."


